site_name: 'Рекомендации по стандартам PHP: PSR'
site_url: 'https://php-psr.ru/'
theme: material
plugins:
    - search
    - meta-descriptions
extra_css:
    - //cdnjs.cloudflare.com/ajax/libs/highlight.js/9.11.0/styles/default.min.css
extra_javascript:
    - https://code.jquery.com/jquery-3.2.1.min.js
    - //cdnjs.cloudflare.com/ajax/libs/highlight.js/9.11.0/highlight.min.js
    - js/init.js
nav:
    - Рекомендации по стандартам PHP (PSR): index.md
    - Принятые:
        - Основной стандарт кодирования PSR-1:
            - Спецификация: accepted/PSR-1-basic-coding-standard.md
        - Общий интерфейс логирования PSR-3:
            - Спецификация: accepted/PSR-3-logger-interface.md
            - Мета-документ: accepted/PSR-3-logger-interface-meta.md
        - Стандарт автозагрузки PSR-4:
            - Спецификация: accepted/PSR-4-autoloader.md
            - Примеры реализации: accepted/PSR-4-autoloader-examples.md
            - Мета-документ: accepted/PSR-4-autoloader-meta.md
        - Интерфейс кэширования PSR-6:
            - Спецификация: accepted/PSR-6-cache.md
            - Мета-документ: accepted/PSR-6-cache-meta.md
        - Интерфейсы HTTP-сообщений PSR-7:
            - Спецификация: accepted/PSR-7-http-message.md
            - Мета-документ: accepted/PSR-7-http-message-meta.md
        - Интерфейс контейнера PSR-11:
            - Спецификация: accepted/PSR-11-container.md
            - Мета-документ: accepted/PSR-11-container-meta.md
        - Расширенное руководство по стилю кодирования PSR-12:
            - Спецификация: accepted/PSR-12-extended-coding-style-guide.md
            - Мета-документ: accepted/PSR-12-extended-coding-style-guide-meta.md
        - Гипермедийные ссылки PSR-13:
            - Спецификация: accepted/PSR-13-links.md
            - Мета-документ: accepted/PSR-13-links-meta.md
        - Диспетчер событий PSR-14:
            - Спецификация: accepted/PSR-14-event-dispatcher.md
            - Мета-документ: accepted/PSR-14-event-dispatcher-meta.md
        - HTTP-обработчики PSR-15:
            - Спецификация: accepted/PSR-15-request-handlers.md
            - Мета-документ: accepted/PSR-15-request-handlers-meta.md
        - Простой кэш PSR-16:
            - Спецификация: accepted/PSR-16-simple-cache.md
            - Мета-документ: accepted/PSR-16-simple-cache-meta.md
        - HTTP-фабрики PSR-17:
            - Спецификация: accepted/PSR-17-http-factory.md
            - Мета-документ: accepted/PSR-17-http-factory-meta.md
        - HTTP-клиент PSR-18:
            - Спецификация: accepted/PSR-18-http-client.md
            - Мета-документ: accepted/PSR-18-http-client-meta.md
    - Черновики:
        - PHPDoc PSR-5:
            - Спецификация: proposed/phpdoc.md
            - Мета-документ: proposed/phpdoc-meta.md
        - Теги PHPDoc PSR-19:
            - Спецификация: proposed/phpdoc-tags.md
            - Мета-документ: proposed/phpdoc-tags-meta.md
        - Часы PSR-20:
            - Спецификация: proposed/clock.md
            - Мета-документ: proposed/clock-meta.md
    - Устаревшие:
        - Стандарт автозагрузки PSR-0: accepted/PSR-0.md
        - Руководство по стилю кодирования PSR-2:
            - Спецификация: accepted/PSR-2-coding-style-guide.md
            - Мета-документ: accepted/PSR-2-coding-style-guide-meta.md
    - Не поддерживается:
        - Удобный интерфейс PSR-8:
            - Спецификация: proposed/psr-8-hug/psr-8-hug.md
            - Мета-документ: proposed/psr-8-hug/PSR-8-hug-meta.md
        - Советы по безопасности PSR-9:
            - Спецификация: proposed/security-reporting-process.md
            - Мета-документ: proposed/security-reporting-process-meta.md
        - Процесс сообщений о безопасности PSR-10:
            - Спецификация: proposed/security-disclosure-publication.md
            - Мета-документ: proposed/security-disclosure-publication-meta.md
    - Регламенты PHP-FIG:
        - Миссия и структура: bylaws/001-mission-and-structure.md
        - Рабочий процесс PSR: bylaws/002-psr-workflow.md
        - Рабочий процесс PER: bylaws/003-per-workflow.md
        - Голосование: bylaws/004-votes.md
        - Выборы и вакансии: bylaws/005-elections-and-vacancies.md
        - Политика лицензирования: bylaws/006-licensing-policies.md
        - Поправки к PSR: bylaws/007-psr-amendments.md
        - Эволюция PSR: bylaws/008-psr-evolution.md
        - Соглашения об именах: bylaws/009-naming-conventions.md
        - Реализация: bylaws/100-implementation.md
    - Лицензия: LICENSE.md
